### ISSUE TITLE
Unreadable error when specifying go dir instead of go.mod

### ISSUE THREAD

**Issue by jakobbraun** [exasol/project-keeper#307]
in a  multi project setup go projects can be in a nested folder.
In that case PK currenty fails with
```
2022-05-18 07:13:23.713 [FINE   ] Executing command 'go list -f {{if not .Indirect}}{{.}}{{end}} -m all' in working dir /home/jakob/exasol/exasol-test-setup-abstraction-server 
Exception in thread "main" java.lang.IllegalStateException: E-PK-CORE-126: Failed to run command 'go list -f {{if not .Indirect}}{{.}}{{end}} -m all', exit code was 1 after PT0.023671S. Output:
''
Error output:
'go: cannot match "all": go.mod file not found in current directory or any parent directory; see 'go help modules'
'
        at com.exasol.projectkeeper.sources.analyze.golang.SimpleProcess.getOutput(SimpleProcess.java:87)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangServices.getModuleInfo(GolangServices.java:132)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangSourceAnalyzer.analyzeSource(GolangSourceAnalyzer.java:51)
        at com.exasol.projectkeeper.sources.analyze.golang.GolangSourceAnalyzer.lambda$analyze$0(GolangSourceAnalyzer.java:40)

```

**Comment by jakobbraun** [comment]
It was something different.
I specified as source: `go-sub-project/`
But correct would be: `go-sub-project/go.mod`

ToDo:
* Add validation that path ends with `go.mod`
