### ISSUE TITLE
Running PK on a Go project fails

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#545]
Example: exasol-driver-go

```
Exception in thread "main" com.vdurmont.semver4j.SemverException: Invalid version (no major version): v1.0.4
        at com.vdurmont.semver4j.Semver.<init>(Semver.java:61)
        at com.vdurmont.semver4j.Semver.<init>(Semver.java:20)
        at com.exasol.projectkeeper.validators.VersionIncrementValidator.isValidSuccessor(VersionIncrementValidator.java:62)
        at com.exasol.projectkeeper.validators.VersionIncrementValidator.validate(VersionIncrementValidator.java:51)
        at com.exasol.projectkeeper.ProjectKeeper.lambda$runValidation$1(ProjectKeeper.java:287)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.exasol.projectkeeper.ProjectKeeper.runValidation(ProjectKeeper.java:288)
        at com.exasol.projectkeeper.ProjectKeeper.runValidationPhases(ProjectKeeper.java:278)
        at com.exasol.projectkeeper.ProjectKeeper.fix(ProjectKeeper.java:260)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.runProjectKeeper(ProjectKeeperLauncher.java:73)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.start(ProjectKeeperLauncher.java:67)
        at com.exasol.projectkeeper.cli.ProjectKeeperLauncher.main(ProjectKeeperLauncher.java:61)
```

**Comment by ckunki** [comment]
Maybe this was the reason for not using `semver` :slightly_smiling_face:
